--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/poggit-orphanage/PurePerms
branches:
- master
- pm5-dev
- multiworld-fix
projects:
  PurePerms:
    path: ""
    icon: icon128.png
...
