# MPEPerms by 64FF00 (xktiverz@gmail.com, @64ff00 for Twitter)

name: MPEPerms
main: XackiGiFF\MPEPerms\MPEPerms
version: 1.0.0
api: [ 5.0.0 ]
load: POSTWORLD
author: "64FF00 & ProjectInfinity | Remake to API 5.0.0 by XackiGiFF"
website: https://github.com/PurePlugins/MPErePerms
permissions:
  MPEPerms:
    description: 'MPErePerms by 64FF00! (Twitter: @64FF00)'
  mperms.command:
    default: op
    description: Allows you to use all MPErePerms commands.
  mperms.command.grpinfo:
    default: op
    description: Allows you to see an info of group
  mperms.command.addgroup:
    default: op
    description: Allows you to add a new group to the groups list.
  mperms.command.addparent:
    default: op
    description: Allows you to add a group to another group inheritance list.
  mperms.command.defgroup:
    default: op
    description: Allows you to set the default group manually.
  mperms.command.fperms:
    default: op
    description: Allows you to find permissions for a specific plugin.
  mperms.command.groups:
    default: op
    description: Allows you to see a list of all groups.
  mperms.command.listgperms:
    default: op
    description: Allows you to see a list of all permissions from a group.
  mperms.command.listuperms:
    default: op
    description: Allows you to see a list of all permissions from a user.
  mperms.command.ppinfo:
    default: true
    description: Allows you to get current MPErePerms information.
  mperms.command.ppreload:
    default: op
    description: Allows you to reload all MPErePerms configurations.
  mperms.command.rmgroup:
    default: op
    description: Allows you to remove a group from the groups list.
  mperms.command.rmparent:
    default: op
    description: Allows you to remove a group from another group inheritance list.
  mperms.command.setgperm:
    default: op
    description: Allows you to add a permission to the group.
  mperms.command.setgroup:
    default: op
    description: Allows you to set group for a user.
  mperms.command.setuperm:
    default: op
    description: Allows you to add a permission to a user.
  mperms.command.unsetgperm:
    default: op
    description: Allows you to remove a permission from the group.
  mperms.command.unsetuperm:
    default: op
    description: Allows you to remove a permission from the user.
  mperms.command.usrinfo:
    default: op
    description: Allows you to see info about a user.
  mperms.noeul:
    default: true
    description: Allows you to access all 'Noeul' related features.
  mperms.noeul.ppsudo:
    default: true
    description: Allows you to use the Noeul 'ppsudo' command.
